version: '3'
name: knowledgebase_lab

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: confdb
      POSTGRES_USER: confdb
      POSTGRES_PASSWORD: confdb
    ports:
      - '5432:5432'
    volumes:
      - './confluence-postgres:/var/lib/postgresql/data'
    networks:
      - knowledgebase

  # confluence-server:
  #   depends_on:
  #     - postgresql
  #   image: atlassian/confluence
  #   ports:
  #     - '8090:8090'
  #     - '8091:8091'
  #   volumes:
  #     - './confluence-home:/var/atlassian/application-data/confluence'
  #   environment:
  #     ATL_JDBC_URL: jdbc:postgresql://postgresql:5432/confdb
  #     ATL_JDBC_USER: confdb
  #     ATL_JDBC_PASSWORD: confdb
  #     ATL_DB_TYPE: postgresql
  #     ATL_DB_DRIVER: org.postgresql.Driver
  #     ATL_DB_SCHEMA_NAME: public
  #   networks:
  #     - knowledgebase


networks:
  knowledgebase:
    external: true